### ISSUE TITLE
Error with implicit conversion. 

### ISSUE THREAD

**Issue by jbray1982** [ChilliCream/greendonut#65]
**Describe the bug**
When trying to convert an IReadOnlyCollection to a Result<IReadOnlyCollection> implicitly in a Select statement, a compilation error occurs. 

**To Reproduce**
The following lines 
`[TestMethod]`
`public void Select_statement_implicit_operator()`
`        {`
`            var strings = new[] { new[] { "TestString" }.ToList() };`
`            var result = strings.Select<IReadOnlyCollection<string>,Result<IReadOnlyCollection<string>>>(x => (Result<IReadOnlyCollection<string>>)(IReadOnlyCollection<string>)x);`
`        }`

result in a compilation error under version 2.0.0-preview5. The same lines compile in version 1.1.0.

**Expected behavior**
No compilation errors occur.

I spent some time trying to figure out why this is the case and was unable to see any reason why this should be an issue.

**Comment by michaelstaib** [comment]
This should now work without the cast .... let me try that one out.

**Comment by rstaib** [comment]
We will remove the `Obsolete` attribute from `Result<>.Reject()` and `Result<>.Resolve()` because it makes some parts easier. 

This should then work again:
```csharp
IReadOnlyCollection<IReadOnlyCollection<string>> strings = new[]
{
    new[] { "TestString" }.ToList()
};
IEnumerable<Result<IReadOnlyCollection<string>>> result = strings
    .Select(Result<IReadOnlyCollection<string>>.Resolve);
```
